### ISSUE TITLE
Support empty password

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch-cloud-azure#1]
When generating keys without passwords, we should be able to handle it.

That means the following should work:

```
  cloud:
      azure:
          private_key: /azure.pk
          certificate: /azure.crt
          subscription_id: subid
  discovery:
          type: azure
```
