### ISSUE TITLE
Support discovery.zen.minimum_master_nodes

### ISSUE THREAD

**Issue by ThomasArdal** [elastic/elasticsearch-cloud-azure#15]
It doesn't seem like the `discovery.zen.minimum_master_nodes` setting works, when used in combination with the azure plugin. I have a cluster where `discovery.zen.minimum_master_nodes: 2` and the following azure config:

``` yaml
cloud: 
  azure: 
   keystore: path_to_keystore
   password: password 
   subscription_id: my_subscription_id
   service_name: my_service

discovery: 
   type: azure
```

When cluster is restarted, only a single node is selected as master.

I'm using v1.0.0.alpha1 (long story). Maybe it is fixed in one of the recent versions?
