### ISSUE TITLE
Installing plugin prevents the elastic search from restarting

### ISSUE THREAD

**Issue by rajinders** [elastic/elasticsearch-cloud-azure#22]
I have followed the installation instructions. I installed the latest version of elastic search(version 1.2.2)
Before installing the plugin my elastic search was running fine. plugin version I installed is 2.3.0
I can do `curl http://localhost:9200` and get a response.

I stopped the service
Installed the latest version of plugin
When I restart the service it does not start. 

Here are my elasticsearch.yml settings

``` yml
cloud:
        azure:
            keystore: /home/elasticsearch/azurekeystore.pkcs12
            password: mypassword
            subscription_id: subscription_guid
            service_name: cldazurees
    discovery:
            type: azure
```

Do I have to specify service_name as cldazurees.cloudapp.net or just cldazurees?

Here is what I see in the elasticsearch.log file

```
[2014-07-21 14:10:11,475][INFO ][node                     ] [Shiva] stopping ...
[2014-07-21 14:10:11,588][INFO ][node                     ] [Shiva] stopped
[2014-07-21 14:10:11,588][INFO ][node                     ] [Shiva] closing ...
[2014-07-21 14:10:11,621][INFO ][node                     ] [Shiva] closed
```

I created the certificate, uploaded it to Azure management portal, I copied the azurekeystore.pkcs12 to the elastic search VM.

If I comment out all the plugin related settings from elasticsearch.yml elastic search starts running again.

Let me know if you have any suggestions for me.

Thanks
