### ISSUE TITLE
Azure plugin certificate too dangerous ?

### ISSUE THREAD

**Issue by peterlimayo** [elastic/elasticsearch-cloud-azure#68]
Hi,

I have played with the azure plugin and am worried that the certificate
placed into Azure management pool can be very powerful. If a cracker
steals the password and keystore from the elasticsearch.yml, would they 
be able to disrupt all the deployments from the same Azure subscription,
even if not related to elasticsearch ? E.g. they could use the keystore,
password to access the subscription fully and delete all the nodes ?

Is there a way to reduce the privilege of the uploaded certificates to
something safer ?

Thanks.

**Comment by dadoonet** [comment]
I do agree. That's the reason I brought up #67.
If doable it will fix that.

**Comment by dadoonet** [comment]
I can confirm that it works really well. Going to propose a PR for #67 so we will have something really more secure and simple to use.

Closing this as duplicate of #67.

**Comment by pwli** [comment]
After trying to keep passwords/keys safe for luks/cryptsetup and other tools,
I was wondering if ES can allow the use of stdin for password at start up ?
For example, if elasticsearch.yml has:
```
cloud:
    ...
             keystore:
                   path: /path/to/azurekeystore.pkcs12
                   password: "<stdin>" or a simple "-"
                   type: pkcs12
```
then it will flag azure plugin to prompt the user to enter a password to continue.
In this case, if someone steals the .yml and keystore file, they won't
be able to get to the certificate.

This won't work if we expect ES to start automatically from a node
reboot. In this case, you just have to put the password in. But this 
could provide some protection than leaving the files out in the open
even if they are unix permission restricted.

My two cents.
