### ISSUE TITLE
readme is wrong when talking about storage configuration.

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-cloud-azure#78]
I'm using 1.5.1 and the following is wrong:

```
To enable Azure repositories, you have first to set your azure storage settings in elasticsearch.yml file:

cloud:
    azure:
        storage:
            account: your_azure_storage_account
            key: your_azure_storage_key
For information, in previous version of the azure plugin, settings were:

cloud:
    azure:
        storage_account: your_azure_storage_account
        storage_key: your_azure_storage_key
```
The previous version is the only version that works for me on 1.5.1
